// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Aplikacija.Migrations
{
    [DbContext(typeof(AplikacijaContext))]
    [Migration("20220428152153_v5.1")]
    partial class v51
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Administrator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Administratori");
                });

            modelBuilder.Entity("Models.Greska", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ID");

                    b.ToTable("Greske");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ban")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Models.Prevoznik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Prevoznici");
                });

            modelBuilder.Entity("Models.RecenzijaPrevoznika", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AutorID")
                        .HasColumnType("int");

                    b.Property<int?>("PrevoznikID")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AutorID");

                    b.HasIndex("PrevoznikID");

                    b.ToTable("RecenzijePrevoznika");
                });

            modelBuilder.Entity("Models.RecenzijaStanice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AutorID")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StanicaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AutorID");

                    b.HasIndex("StanicaID");

                    b.ToTable("RecenzijeStanice");
                });

            modelBuilder.Entity("Models.Stanica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Stanice");
                });

            modelBuilder.Entity("Models.Voznja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int?>("KrajnaStanicaID")
                        .HasColumnType("int");

                    b.Property<int?>("PocetnaStanicaID")
                        .HasColumnType("int");

                    b.Property<int?>("PrevoznikID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Termin")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("KrajnaStanicaID");

                    b.HasIndex("PocetnaStanicaID");

                    b.HasIndex("PrevoznikID");

                    b.ToTable("Voznje");
                });

            modelBuilder.Entity("Models.RecenzijaPrevoznika", b =>
                {
                    b.HasOne("Models.Korisnik", "Autor")
                        .WithMany("recenzijePrevoznika")
                        .HasForeignKey("AutorID");

                    b.HasOne("Models.Prevoznik", "Prevoznik")
                        .WithMany()
                        .HasForeignKey("PrevoznikID");

                    b.Navigation("Autor");

                    b.Navigation("Prevoznik");
                });

            modelBuilder.Entity("Models.RecenzijaStanice", b =>
                {
                    b.HasOne("Models.Korisnik", "Autor")
                        .WithMany("recenzijeStanice")
                        .HasForeignKey("AutorID");

                    b.HasOne("Models.Stanica", "Stanica")
                        .WithMany()
                        .HasForeignKey("StanicaID");

                    b.Navigation("Autor");

                    b.Navigation("Stanica");
                });

            modelBuilder.Entity("Models.Voznja", b =>
                {
                    b.HasOne("Models.Korisnik", null)
                        .WithMany("kupljeneKarte")
                        .HasForeignKey("KorisnikID");

                    b.HasOne("Models.Stanica", "KrajnaStanica")
                        .WithMany()
                        .HasForeignKey("KrajnaStanicaID");

                    b.HasOne("Models.Stanica", "PocetnaStanica")
                        .WithMany()
                        .HasForeignKey("PocetnaStanicaID");

                    b.HasOne("Models.Prevoznik", "Prevoznik")
                        .WithMany("poslatiZahtevi")
                        .HasForeignKey("PrevoznikID");

                    b.Navigation("KrajnaStanica");

                    b.Navigation("PocetnaStanica");

                    b.Navigation("Prevoznik");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Navigation("kupljeneKarte");

                    b.Navigation("recenzijePrevoznika");

                    b.Navigation("recenzijeStanice");
                });

            modelBuilder.Entity("Models.Prevoznik", b =>
                {
                    b.Navigation("poslatiZahtevi");
                });
#pragma warning restore 612, 618
        }
    }
}
